# -------------------------------------------------
# ref: https://mailtrap.io/blog/python-send-email/
# -------------------------------------------------
import smtplib # smptp
from email.mime.text import MIMEText

def send_email():
    # Configuration
    port = 587
    smtp_server = "smtp.google.com"
    login = "api"  # Your login generated by Mailtrap
    password = "1a2b3c4d5e6f7g"  # Your password generated by Mailtrap

    sender_email = "mailtrap@example.com"
    receiver_email = "new@example.com"

    # Plain text content
    text = """\
    Hi,
    Check out the new post on the Mailtrap blog:
    SMTP Server for Testing: Cloud-based or Local?
    https://blog.mailtrap.io/2018/09/27/cloud-or-local-smtp-server/
    Feel free to let us know what content would be useful for you!
    """

    # Create MIMEText object
    message = MIMEText(text, "plain")
    message["Subject"] = "Plain text email"
    message["From"] = sender_email
    message["To"] = receiver_email

    # Send the email
    with smtplib.SMTP(smtp_server, port) as server:
        server.starttls()  # Secure the connection
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())
# -------------------------------------------------
# -------------------------------------------------

import datetime as dt

now = dt.datetime.now()
print(type(now))